name: Update README with Notion Notes

on:
  push:
    paths:
      - 'notion_links.txt'   # 👈 only trigger when this changes
  schedule:
    - cron: '0 0 * * *'      # daily at 00:00 UTC
  workflow_dispatch:          # manual run

permissions:
  contents: write   # allow GitHub Actions bot to push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # keep token for push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (manual)
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 cohere

      - name: Run updater
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          python update_readme.py

      - name: Show README after update
        run: |
          echo "====== README.md ======"
          cat README.md

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md summaries.json || true
          git commit -m "Auto-update README (Code-Snax)" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
