name: Update README with Notion Notes

on:
  push:
    paths:
      - 'notion_links.txt'
      - 'update_readme.py'
      - '.github/workflows/update-readme.yml'
      - 'README.md'
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC
  workflow_dispatch:       # manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          python update_readme.py

      - name: Commit changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md summaries.json || true
          git commit -m "Auto-update README (Code-Snax)" || echo "No changes to commit"
          git push || echo "No changes to push"
